/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bazar;


import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Tomáš
 */
public class Grafika extends javax.swing.JFrame {
    /**
     * Creates new form Grafika
     */
    private Inzerat databaza;
    public Grafika() throws IOException {
        this.initComponents();
        this.datumLB.setText("Dátum: " + new Date().toString());
        this.databaza = new Inzerat();
        try { //pokus nacitat databazu zo suboru, v pripade neuspechu, vyhodí výnimku
            this.databaza.nacitajDatabazu();
            this.nacitanieL.setText("Databáza úspešné načítaná!");
        } catch (FileNotFoundException ex) {
            this.nacitanieL.setText("Nepodarilo sa načítať databázu, skúste znova. Ak sa tým problém nevyrieši, kontaktujte správcu Toša.");
            this.exL.setText("Chyba: " +  ex.getMessage());
        }
        this.setTitle("Bazár");
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nakupBT = new javax.swing.JButton();
        predajBT = new javax.swing.JButton();
        koniecBT = new javax.swing.JButton();
        autorLB = new javax.swing.JLabel();
        datumLB = new javax.swing.JLabel();
        nacitanieL = new javax.swing.JLabel();
        exL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dobrý deň. Vitajte v mojom malom bazáre. Pre pokračovanie zvoľte možnosť v menu.");
        jLabel1.setToolTipText("");

        nakupBT.setText(" Nákup v bazári");
        nakupBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nakupBTActionPerformed(evt);
            }
        });

        predajBT.setText("Pridať inzerát ");
        predajBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                predajBTActionPerformed(evt);
            }
        });

        koniecBT.setText("Koniec");
        koniecBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koniecBTActionPerformed(evt);
            }
        });

        autorLB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        autorLB.setForeground(new java.awt.Color(0, 0, 102));
        autorLB.setText("Made by Tomáš Cvinček 5zy012 2018");

        datumLB.setText("jLabel2");

        nacitanieL.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(datumLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 399, Short.MAX_VALUE)
                        .addComponent(autorLB))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(predajBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(koniecBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nakupBT, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(nacitanieL)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exL)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nacitanieL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exL)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nakupBT)
                        .addGap(18, 18, 18)
                        .addComponent(predajBT)
                        .addGap(18, 18, 18)
                        .addComponent(koniecBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(autorLB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(datumLB)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(null, "Naozaj chceš skončiť?", "Koniec", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void koniecBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koniecBTActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(null, "Naozaj chceš skončiť?", "Koniec", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_koniecBTActionPerformed

    private void nakupBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nakupBTActionPerformed
        // TODO add your handling code here:
        NakupGrafika nakup = NakupGrafika.getInstanceNakupGrafika(this.databaza); // vytvorenie instancie noveho okna
        nakup.setVisible(true);
    }//GEN-LAST:event_nakupBTActionPerformed

    private void predajBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_predajBTActionPerformed
        // TODO add your handling code here:
        PredajGrafika predaj = PredajGrafika.getInstancePredajGrafika(this.databaza); // vytvorenie instancie noveho okna
        predaj.setVisible(true);
    }//GEN-LAST:event_predajBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Grafika().setVisible(true);
                } catch (IOException ex) {
                    ex.getMessage();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autorLB;
    private javax.swing.JLabel datumLB;
    private javax.swing.JLabel exL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton koniecBT;
    private javax.swing.JLabel nacitanieL;
    private javax.swing.JButton nakupBT;
    private javax.swing.JButton predajBT;
    // End of variables declaration//GEN-END:variables
}
