/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bazaar;

import java.awt.GridLayout;
import java.awt.Label;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Tomáš
 */
public class Desired extends javax.swing.JFrame {
    private ArrayList<IForSale> desired;
    private Listing listing;
    private JButton[] buttons;

    /**
     * Creates new form Desired
     */
    /**
     * Konstruktor automaticky generuje buttony a priradzuje im listenery
     * Po stlacenie jednotlivych buttonov sa podhodi otazka k kúpe
     * Ak stlacime ano, inzerat sa odstrani z databazy a databaza sa nanovo nahra do suboru 
     * @param desired
     * @param listing 
     */
    public Desired(ArrayList<IForSale> desired, Listing listing) {
        this.initComponents();
        this.listing = listing;
        this.desired = new ArrayList<IForSale>();
        this.desired = desired;
        this.buttons = new JButton[this.desired.size()];
        System.out.println(this.listing.toString());
        System.out.println(this.desired);
        JFrame okno = new JFrame("Výber inzerátu");
        okno.setVisible(true);
        if (this.desired.size() != 0) {
            for (int i = 0; i < this.buttons.length; i++) {
                JButton btn = (new JButton(this.desired.get(i).toString()));
                okno.add(btn);
                btn.addActionListener(new java.awt.event.ActionListener() {
                    @Override
                    public void actionPerformed(java.awt.event.ActionEvent e) {
                        String listingText = btn.getText();
                        for (int i = 0; i < listing.getCount(); i++) {
                            if (true) {
                                if (listing.getListing(i).toString().equals(listingText)) {
                                    int reply = JOptionPane.showConfirmDialog(null, listingText + "\n" + "Naozaj chceš kúpiť tento inzerát?", "Záväzná kúpa", JOptionPane.YES_NO_OPTION);
                                    if (reply == JOptionPane.YES_OPTION) {
                                        listing.removeListing(i);
                                        JOptionPane.showMessageDialog(null, "Predané, ďakujeme za transakciu!");
                                        try {
                                            listing.saveDatabase();
                                            okno.dispose();
                                        } catch (IOException ex) {
                                            JOptionPane.showMessageDialog(null, "Nastala chyba, je nám ľúto");
                                            okno.dispose();
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                );
                this.buttons[i] = btn;   
            }
            okno.setLayout(new GridLayout(this.desired.size(), 0));
            okno.pack();
        } else {
            okno.add(new Label("Žiadne inzeráty nevyhovujú Vaším podmienkam."));
            okno.pack();
        }
        okno.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        okno.addWindowListener (new WindowAdapter() { 
            @Override 
            public void windowClosing(WindowEvent e) {
                int reply = JOptionPane.showConfirmDialog(null, "Naozaj chceš skončiť, tvoje dáta sa stratia", "Koniec", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                    okno.dispose();
                }
            }
        }
        );
    }
    
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desired.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desired.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desired.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desired.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desired(new ArrayList<IForSale>(), new Listing()).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
