/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bazaar;

import electronics.ElectronicDevice;
import electronics.Electronics;
import electronics.Mobile;
import electronics.Computer;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import onWheels.Car;
import onWheels.Bus;
import onWheels.Truck;
import onWheels.Motorcycle;
import onWheels.Vehicle;
import gardenMachines.LawnMower;
import gardenMachines.BrushCutter;
import gardenMachines.Chainsaw;
import gardenMachines.Machine;

/**
 *
 * @author Tomáš
 */
public class PurchaseGraphics extends javax.swing.JFrame {
    private Listing database;
    private ArrayList <IForSale> auxiliary;
    private static PurchaseGraphics instance = null;
    /**
     * Creates new form PurchaseGraphics
     */
    
    public static PurchaseGraphics getInstance (Listing listing) {
        if (instance == null) {
            instance = new PurchaseGraphics(listing);
            return instance;
        } else {
            return instance;
        }
    }
    private PurchaseGraphics(Listing listing) {
        instance = this;
        this.initComponents();
        this.database = listing;
        this.auxiliary = new ArrayList<IForSale>();
        this.choiceCB.setVisible(false);
        this.L00.setVisible(false);
        this.L10.setVisible(false);
        this.L20.setVisible(false);
        this.L30.setVisible(false);
        this.L40.setVisible(false);
        this.L50.setVisible(false);
        this.L03.setVisible(false);
        this.L11.setVisible(false);
        this.L21.setVisible(false);
        this.L01.setVisible(false);
        this.TF00.setVisible(false);
        this.TF10.setVisible(false);
        this.TF20.setVisible(false);
        this.TF30.setVisible(false);
        this.TF40.setVisible(false);
        this.TF50.setVisible(false);
        this.TF10.setVisible(false);
        this.TF11.setVisible(false);
        this.TF21.setVisible(false);
        this.TF30.setVisible(false);
        this.TF03.setVisible(false);
        this.TF01.setVisible(false);        
    }
    /**
    * Sets all components to invisible
    */
    public void setInvisible() {
        this.L00.setVisible(false);
        this.L10.setVisible(false);
        this.L20.setVisible(false);
        this.L30.setVisible(false);
        this.L40.setVisible(false);
        this.L50.setVisible(false);
        this.L03.setVisible(false);
        this.L11.setVisible(false);
        this.L21.setVisible(false);
        this.L01.setVisible(false);
        this.TF00.setVisible(false);
        this.TF10.setVisible(false);
        this.TF20.setVisible(false);
        this.TF30.setVisible(false);
        this.TF40.setVisible(false);
        this.TF50.setVisible(false);
        this.TF10.setVisible(false);
        this.TF11.setVisible(false);
        this.TF21.setVisible(false);
        this.TF30.setVisible(false);
        this.TF03.setVisible(false);
        this.TF01.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        searchB = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        categoryCB = new javax.swing.JComboBox<>();
        choiceLabel = new javax.swing.JLabel();
        choiceCB = new javax.swing.JComboBox<>();
        L00 = new javax.swing.JLabel();
        L10 = new javax.swing.JLabel();
        L20 = new javax.swing.JLabel();
        L30 = new javax.swing.JLabel();
        L40 = new javax.swing.JLabel();
        L50 = new javax.swing.JLabel();
        L03 = new javax.swing.JLabel();
        TF00 = new javax.swing.JTextField();
        TF20 = new javax.swing.JTextField();
        TF10 = new javax.swing.JTextField();
        TF30 = new javax.swing.JTextField();
        TF40 = new javax.swing.JTextField();
        TF50 = new javax.swing.JTextField();
        TF03 = new javax.swing.JTextField();
        L01 = new javax.swing.JLabel();
        L11 = new javax.swing.JLabel();
        L21 = new javax.swing.JLabel();
        TF01 = new javax.swing.JTextField();
        TF11 = new javax.swing.JTextField();
        TF21 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Select from the menu what you want to buy.");

        searchB.setText("Search");
        searchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Choose what you are interested in");

        categoryCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vehicles", "Garden machines", "Electronics" }));
        categoryCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryCBActionPerformed(evt);
            }
        });

        choiceLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        choiceCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceCBActionPerformed(evt);
            }
        });

        L00.setText("Brand");

        L10.setText("Model");

        L20.setText("Year of manufacture");

        L30.setText("Power");

        L40.setText("Power input");

        L50.setText("Driven km");

        L03.setText("Max. price");

        TF00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF00ActionPerformed(evt);
            }
        });

        TF10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF10ActionPerformed(evt);
            }
        });

        TF03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF03ActionPerformed(evt);
            }
        });

        L01.setText("jLabel2");

        L11.setText("jLabel3");

        L21.setText("jLabel4");

        TF01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF01ActionPerformed(evt);
            }
        });

        TF21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(categoryCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(578, 578, 578))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(choiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(choiceCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(L10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(L30, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(L40, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(L50, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(L00, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF00)
                            .addComponent(TF20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TF30)
                            .addComponent(TF50)
                            .addComponent(TF40, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TF10))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(263, 263, 263)
                                .addComponent(searchB, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(219, 219, 219))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(L01)
                                        .addComponent(L21)
                                        .addComponent(L11))
                                    .addComponent(L03))
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TF03, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(TF21, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF11, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF01, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(choiceCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choiceLabel))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L00, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L01)
                    .addComponent(TF01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L10)
                    .addComponent(TF10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L11)
                    .addComponent(TF11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L20)
                    .addComponent(TF20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L21)
                    .addComponent(TF21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L30)
                    .addComponent(TF30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L40)
                    .addComponent(TF40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L03, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchB)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(null, "Do you really want to quit, your data will be lost", "End", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing
    /**
     * Based on the selection from the combo box, shows the relevant labels and text fields
    */
    private void choiceCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceCBActionPerformed
        // TODO add your handling code here:
        if (this.categoryCB.getSelectedItem().equals("Vehicles")) {
            this.setInvisible();
            this.L00.setVisible(true);
            this.L00.setText("Brand");
            this.TF00.setVisible(true);
            this.L10.setVisible(true);
            this.L10.setText("Model");
            this.TF10.setVisible(true);
            this.L20.setVisible(true);
            this.L20.setText("Year of manufacture");
            this.TF20.setVisible(true);
            this.L30.setVisible(true);
            this.L30.setText("Min. power(kW)");
            this.TF30.setVisible(true);
            this.L40.setVisible(true);
            this.L40.setText("Driven km");
            this.TF40.setVisible(true);
            this.L03.setVisible(true);
            this.L03.setText("Max. price (€)");
            this.TF03.setVisible(true);
            if (this.choiceCB.getSelectedItem() != null) {
                if (this.choiceCB.getSelectedItem().equals("Car")) {
                    this.L01.setVisible(true);
                    this.L01.setText("Body type");
                    this.TF01.setVisible(true);
                } else {
                    this.L01.setVisible(false);
                    this.TF01.setVisible(false);
                }  
            }
        } else if (this.categoryCB.getSelectedItem().equals("Garden machines")) {
            this.setInvisible();
            this.L00.setVisible(true);
            this.L00.setText("Brand");
            this.TF00.setVisible(true);
            this.L10.setVisible(true);
            this.L10.setText("Year of manufacture");
            this.TF10.setVisible(true);
            this.L30.setVisible(true);
            this.L30.setText("Min. power input(kW)");
            this.TF30.setVisible(true);
            this.L03.setVisible(true);
            this.L03.setText("Max. price (€)");
            this.TF03.setVisible(true);
        } else if (this.categoryCB.getSelectedItem().equals("Electronics")) {
            this.setInvisible();
            this.L00.setVisible(true);
            this.L00.setText("Brand");
            this.TF00.setVisible(true);
            this.L10.setVisible(true);
            this.L10.setText("Year of manufacture");
            this.TF10.setVisible(true);
            this.L03.setVisible(true);
            this.L03.setText("Max. price (€)");
            this.TF03.setVisible(true);
            if (this.choiceCB.getSelectedItem() != null) {
                if (this.choiceCB.getSelectedItem().equals("Computer") || this.choiceCB.getSelectedItem().equals("Mobile")) {
                    this.L40.setVisible(true);
                    this.L40.setText("Processor freq. (MHz)");
                    this.TF40.setVisible(true);
                    this.L01.setVisible(true);
                    this.L01.setText("RAM (GB)");
                    this.TF01.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_choiceCBActionPerformed
    /**
     * Shows the appropriate combo box based on selection from the parent combo box
     * @param  
     */
    private void categoryCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryCBActionPerformed
        // TODO add your handling code here:
        if (this.categoryCB.getSelectedIndex() == 0) {
            this.choiceLabel.setText("Select vehicle type");
            this.choiceCB.removeAllItems();
            this.choiceCB.setVisible(true);
            this.choiceCB.insertItemAt("Car", 0);
            this.choiceCB.insertItemAt("Motorcycle", 1);
            this.choiceCB.insertItemAt("Truck", 2);
            this.choiceCB.insertItemAt("Bus", 3);
        } else if (this.categoryCB.getSelectedIndex() == 1) {
            this.choiceLabel.setText("Select machine type");
            this.choiceCB.removeAllItems();
            this.choiceCB.setVisible(true);
            this.choiceCB.insertItemAt("Lawn Mower", 0);
            this.choiceCB.insertItemAt("Brush Cutter", 1);
            this.choiceCB.insertItemAt("Chainsaw", 2);
        } else if (this.categoryCB.getSelectedIndex() == 2) {
            this.choiceLabel.setText("Select electronics type");
            this.choiceCB.removeAllItems();
            this.choiceCB.setVisible(true);
            this.choiceCB.insertItemAt("Computer", 0);
            this.choiceCB.insertItemAt("Mobile", 1);
            this.choiceCB.insertItemAt("Other", 2);
        } else {
            this.choiceLabel.setText("");
            this.choiceCB.removeAllItems();
            this.choiceCB.setVisible(false);
        }
    }//GEN-LAST:event_categoryCBActionPerformed

    private void TF03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF03ActionPerformed

    private void TF00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF00ActionPerformed

    private void TF01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF01ActionPerformed

    private void TF21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF21ActionPerformed
    /**
     * When the button is pressed, all information is collected from the text fields to refine the search.
     * In case of an error, various types of exceptions are thrown.
     * Finally, with the collected data, a helper method is called whose parameters are the refinement details.
     * If the collected parameters do not match any listing, a custom InvalidSearchParametersException is thrown.
    */
    private void searchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBActionPerformed
        // TODO add your handling code here:
        int moze = 0;
        String brand = "";
        String model = "";
        int yearOfManufacture = 0;
        int power = 0;
        int drivenKm = Integer.MAX_VALUE;
        int price = Integer.MAX_VALUE;
        String bodyType = ""; 
        int frequency = 0;
        double ram = 0;
        if (this.categoryCB.getSelectedItem().equals("Vehicles")) {
            try {
                if (this.choiceCB.getSelectedItem().equals("Car")) {
                    brand = "";
                    model = "";
                    yearOfManufacture = 0;
                    power = 0;
                    drivenKm = Integer.MAX_VALUE;
                    price = Integer.MAX_VALUE;
                    bodyType = ""; 
                    frequency = 0;
                    ram = 0;
                    brand = this.TF00.getText();
                    model = this.TF10.getText();
                    try {
                        if (this.TF20.getText().isEmpty()) {
                            yearOfManufacture = 0;
                        } else {
                            if (Integer.parseInt(this.TF20.getText()) > 0) {
                                yearOfManufacture = Integer.parseInt(this.TF20.getText());
                            } else {
                                yearOfManufacture = Integer.parseInt("invalid");
                                moze++;
                            }
                        }
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Invalid year of manufacture");
                        moze++;
                    }
                    try {
                        if (this.TF40.getText().isEmpty()) {
                            drivenKm = Integer.MAX_VALUE;;
                        } else {
                            if (Integer.parseInt(this.TF40.getText()) > 0) { 
                                drivenKm = Integer.parseInt(this.TF40.getText());
                            } else {
                                drivenKm = Integer.parseInt("invalid");
                            }
                        }
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Invalid driven kilometres");
                        moze++;
                    }
                    try {
                        if (this.TF30.getText().isEmpty()) {
                            power = 0;
                        } else {
                            if (Integer.parseInt(this.TF30.getText()) > 0) {
                                power = Integer.parseInt(this.TF30.getText());
                            } else {
                                power = Integer.parseInt("invalid");     
                            }
                        }
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Invalid power");
                        moze++;
                    }
                    try {
                        if (this.TF03.getText().isEmpty()) {
                            price = Integer.MAX_VALUE;;
                        } else {
                            if (Integer.parseInt(this.TF03.getText()) > 0) {
                                price = Integer.parseInt(this.TF03.getText());
                            } else {
                                price = Integer.parseInt("invalid");
                            }
                        }
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Invalid price");
                        moze++;
                    }
                    bodyType = this.TF01.getText();
                } else {
                    brand = "";
                    model = "";
                    yearOfManufacture = 0;
                    power = 0;
                    drivenKm = Integer.MAX_VALUE;
                    price = Integer.MAX_VALUE;
                    bodyType = "";
                    frequency = 0;
                    ram = 0;
                    brand = this.TF00.getText();
                    model = this.TF10.getText();
                    try {
                        if (this.TF20.getText().isEmpty()) {
                            yearOfManufacture = 0;
                        } else {
                            if (Integer.parseInt(this.TF20.getText()) > 0) {
                                yearOfManufacture = Integer.parseInt(this.TF20.getText());
                            } else {
                                yearOfManufacture = Integer.parseInt("invalid");
                            }
                        }
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Invalid year of manufacture");
                        moze++;
                    }
                    try {
                        if (this.TF40.getText().isEmpty()) {
                            drivenKm = Integer.MAX_VALUE;;
                        } else {
                            if (Integer.parseInt(this.TF40.getText()) > 0) { 
                                drivenKm = Integer.parseInt(this.TF40.getText());
                            } else {
                                drivenKm = Integer.parseInt("invalid");
                            }
                        }
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Invalid driven kilometres");
                        moze++;
                    }
                    try {
                        if (this.TF30.getText().isEmpty()) {
                            power = 0;
                        } else {
                            if (Integer.parseInt(this.TF30.getText()) > 0) {
                                power = Integer.parseInt(this.TF30.getText());
                            } else {
                                power = Integer.parseInt("invalid");     
                            }
                        }
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Invalid power");
                        moze++;
                    }
                    try {
                        if (this.TF03.getText().isEmpty()) {
                            price = Integer.MAX_VALUE;
                        } else {
                            if (Integer.parseInt(this.TF03.getText()) > 0) {
                                price = Integer.parseInt(this.TF03.getText());
                            } else {
                                price = Integer.parseInt("invalid");
                            }
                        }
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Invalid price");
                        moze++;
                    }
                }
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(null, "Incorrect parameters");
                moze++;
            } 
        } else if (this.categoryCB.getSelectedItem().equals("Garden machines")) {
            brand = "";
            model = "";
            yearOfManufacture = 0;
            power = 0;
            drivenKm = Integer.MAX_VALUE;
            price = Integer.MAX_VALUE;
            bodyType = ""; 
            frequency = 0;
            ram = 0;
            brand = this.TF00.getText();
            try {
                try {
                    if (this.TF20.getText().isEmpty()) {
                        yearOfManufacture = 0;
                    } else {
                        if (Integer.parseInt(this.TF20.getText()) > 0) {
                            yearOfManufacture = Integer.parseInt(this.TF20.getText());
                        } else {
                            yearOfManufacture = Integer.parseInt("invalid");
                        }
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Invalid year of manufacture");
                    moze++;
                }
                try {
                    if (this.TF30.getText().isEmpty()) {
                        power = 0;
                    } else {
                        if (Integer.parseInt(this.TF30.getText()) > 0) {
                            power = Integer.parseInt(this.TF30.getText());
                        } else {
                            power = Integer.parseInt("invalid");     
                        }
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Invalid power input");
                    moze++;
                }
                try {
                    if (this.TF03.getText().isEmpty()) {
                        price = Integer.MAX_VALUE;
                    } else {
                        if (Integer.parseInt(this.TF03.getText()) > 0) {
                            price = Integer.parseInt(this.TF03.getText());
                        } else {
                            price = Integer.parseInt("invalid");
                        }
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Invalid price");
                    moze++;
                }       
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(null, "Incorrect parameters");
                moze++;
            }
        } else if (this.categoryCB.getSelectedItem().equals("Electronics")) {
            brand = "";
            model = "";
            yearOfManufacture = 0;
            power = 0;
            drivenKm = Integer.MAX_VALUE;
            price = Integer.MAX_VALUE;
            bodyType = ""; 
            frequency = 0;
            ram = 0;
            brand = this.TF00.getText();
            try {
                try {
                    if (this.TF20.getText().isEmpty()) {
                        yearOfManufacture = 0;
                    } else {
                        if (Integer.parseInt(this.TF20.getText()) > 0) {
                            yearOfManufacture = Integer.parseInt(this.TF20.getText());
                        } else {
                            yearOfManufacture = Integer.parseInt("invalid");
                        }
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Invalid year of manufacture");
                    moze++;
                }
                try {
                    if (this.TF03.getText().isEmpty()) {
                        price = Integer.MAX_VALUE;
                    } else {
                        if (Integer.parseInt(this.TF03.getText()) > 0) {
                            price = Integer.parseInt(this.TF03.getText());
                        } else {
                            price = Integer.parseInt("invalid");
                        }
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Invalid price");
                    moze++;
                }
                if (!this.choiceCB.getSelectedItem().equals("Other")) {
                    try {
                        if (this.TF40.getText().isEmpty()) {
                            frequency = 0;
                        } else {
                            if (Integer.parseInt(this.TF40.getText()) > 0) {
                                frequency = Integer.parseInt(this.TF40.getText());
                            } else {
                                frequency = Integer.parseInt("invalid");
                            }
                        }
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Invalid frequency");
                        moze++;
                    }
                    try {
                        if (this.TF01.getText().isEmpty()) {
                            ram = 0;
                        } else {
                            if (Integer.parseInt(this.TF01.getText()) > 0) {
                                ram = Double.parseDouble(this.TF01.getText());
                            } else {
                                ram = Double.parseDouble("invalid");
                            }
                        }
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Invalid RAM");
                        moze++;
                    }
                }
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(null, "Incorrect parameters"); 
                moze++;
            }
        }
        this.auxiliary.removeAll(this.auxiliary);
        if (moze == 0) {
            ArrayList<IForSale> results = new ArrayList<>();
            int z = 0;
            try {
                results = this.search("" + this.categoryCB.getSelectedItem(), "" + this.choiceCB.getSelectedItem(), brand, model, yearOfManufacture, power, drivenKm, price, bodyType, frequency, ram);
            } catch (InvalidSearchParametersException ex) {
                JOptionPane.showMessageDialog(null, "We found nothing.\n" + ex.getMessage());   
                z++;
            }
            if (z == 0) {
                Desired listings = new Desired(results, this.database);
            }
        }
    }//GEN-LAST:event_searchBActionPerformed
    
    /**
     * Complex method for searching desired listings.
     * Based on the method parameters, searches the database for desired listings matching the conditions.
     * Returns an ArrayList containing only the matching listings.
     * @param type
     * @param subtype
     * @param brand
     * @param model
     * @param yearOfManufacture
     * @param power
     * @param drivenKm
     * @param price
     * @param bodyType
     * @param frequency
     * @param ram
     * @return ArrayList<IForSale>
     */
    private ArrayList<IForSale> search(String type, String subtype, String brand, String model, int yearOfManufacture, int power, int drivenKm, int price, String bodyType, int frequency, double ram) {
        if (type.equals("Vehicles")) {
            if (true) {
                if (!brand.isEmpty()) {
                    if (!model.isEmpty()) {
                        if (!bodyType.isEmpty()) {
                            for (int i = 0; i < this.database.getCount(); i++) {
                                if (this.database.getListing(i) instanceof Vehicle) {
                                    if (((Vehicle)this.database.getListing(i)).getBrand().equals(brand)) {
                                        if (((Vehicle)this.database.getListing(i)).getModel().equals(model)) {
                                            if (((Vehicle)this.database.getListing(i)).getBodyType().equals(bodyType)) {
                                                if (((Vehicle)this.database.getListing(i)).getYearOfManufacture() > yearOfManufacture) {
                                                    if (((Vehicle)this.database.getListing(i)).getDrivenKm() < drivenKm) {
                                                        if (((Vehicle)this.database.getListing(i)).getPower() > power) {
                                                            if (((Vehicle)this.database.getListing(i)).getPrice() < price) {
                                                                if (subtype.equals("Car")) {
                                                                    if (this.database.getListing(i) instanceof Car) {
                                                                        this.auxiliary.add(this.database.getListing(i));
                                                                    }
                                                                } else if (subtype.equals("Motorcycle")) {
                                                                    if (this.database.getListing(i) instanceof Motorcycle) {
                                                                        this.auxiliary.add(this.database.getListing(i));
                                                                    }
                                                                } else if (subtype.equals("Truck")) {
                                                                    if (this.database.getListing(i) instanceof Truck) {
                                                                        this.auxiliary.add(this.database.getListing(i));
                                                                    }
                                                                } else {
                                                                    if (this.database.getListing(i) instanceof Bus) {
                                                                        this.auxiliary.add(this.database.getListing(i));
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        } else {
                            for (int i = 0; i < this.database.getCount(); i++) {
                                if (this.database.getListing(i) instanceof Vehicle) {
                                    if (((Vehicle)this.database.getListing(i)).getBrand().equals(brand)) {
                                        if (((Vehicle)this.database.getListing(i)).getModel().equals(model)) {
                                            if (((Vehicle)this.database.getListing(i)).getYearOfManufacture() > yearOfManufacture) {
                                                if (((Vehicle)this.database.getListing(i)).getDrivenKm() < drivenKm) {
                                                    if (((Vehicle)this.database.getListing(i)).getPower() > power) {
                                                        if (((Vehicle)this.database.getListing(i)).getPrice() < price) {
                                                            if (subtype.equals("Car")) {
                                                                if (this.database.getListing(i) instanceof Car) {
                                                                    this.auxiliary.add(this.database.getListing(i));
                                                                }
                                                            } else if (subtype.equals("Motorcycle")) {
                                                                if (this.database.getListing(i) instanceof Motorcycle) {
                                                                    this.auxiliary.add(this.database.getListing(i));
                                                                }
                                                            } else if (subtype.equals("Truck")) {
                                                                if (this.database.getListing(i) instanceof Truck) {
                                                                    this.auxiliary.add(this.database.getListing(i));
                                                                }
                                                            } else {
                                                                if (this.database.getListing(i) instanceof Bus) {
                                                                    this.auxiliary.add(this.database.getListing(i));
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    } else {
                        if (!bodyType.isEmpty()) {
                            for (int i = 0; i < this.database.getCount(); i++) {
                                if (this.database.getListing(i) instanceof Vehicle) {
                                    if (((Vehicle)this.database.getListing(i)).getBrand().equals(brand)) {
                                        if (true) {
                                            if (((Vehicle)this.database.getListing(i)).getBodyType().equals(bodyType)) {
                                                if (((Vehicle)this.database.getListing(i)).getYearOfManufacture() > yearOfManufacture) {
                                                    if (((Vehicle)this.database.getListing(i)).getDrivenKm() < drivenKm) {
                                                        if (((Vehicle)this.database.getListing(i)).getPower() > power) {
                                                            if (((Vehicle)this.database.getListing(i)).getPrice() < price) {
                                                                if (subtype.equals("Car")) {
                                                                    if (this.database.getListing(i) instanceof Car) {
                                                                        this.auxiliary.add(this.database.getListing(i));
                                                                    }
                                                                } else if (subtype.equals("Motorcycle")) {
                                                                    if (this.database.getListing(i) instanceof Motorcycle) {
                                                                        this.auxiliary.add(this.database.getListing(i));
                                                                    }
                                                                } else if (subtype.equals("Truck")) {
                                                                    if (this.database.getListing(i) instanceof Truck) {
                                                                        this.auxiliary.add(this.database.getListing(i));
                                                                    }
                                                                } else {
                                                                    if (this.database.getListing(i) instanceof Bus) {
                                                                        this.auxiliary.add(this.database.getListing(i));
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        } else {
                            for (int i = 0; i < this.database.getCount(); i++) {
                                if (this.database.getListing(i) instanceof Vehicle) {
                                    if (((Vehicle)this.database.getListing(i)).getBrand().equals(brand)) {
                                        if (true) {
                                            if (((Vehicle)this.database.getListing(i)).getYearOfManufacture() > yearOfManufacture) {
                                                if (((Vehicle)this.database.getListing(i)).getDrivenKm() < drivenKm) {
                                                    if (((Vehicle)this.database.getListing(i)).getPower() > power) {
                                                        if (((Vehicle)this.database.getListing(i)).getPrice() < price) {
                                                            if (subtype.equals("Car")) {
                                                                if (this.database.getListing(i) instanceof Car) {
                                                                    this.auxiliary.add(this.database.getListing(i));
                                                                }
                                                            } else if (subtype.equals("Motorcycle")) {
                                                                if (this.database.getListing(i) instanceof Motorcycle) {
                                                                    this.auxiliary.add(this.database.getListing(i));
                                                                }
                                                            } else if (subtype.equals("Truck")) {
                                                                if (this.database.getListing(i) instanceof Truck) {
                                                                    this.auxiliary.add(this.database.getListing(i));
                                                                }
                                                            } else {
                                                                if (this.database.getListing(i) instanceof Bus) {
                                                                    this.auxiliary.add(this.database.getListing(i));
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                } else {
                    if (!model.isEmpty()) {
                        if (!bodyType.isEmpty()) {
                            for (int i = 0; i < this.database.getCount(); i++) {
                                if (this.database.getListing(i) instanceof Vehicle) {
                                    if (true) {
                                        if (((Vehicle)this.database.getListing(i)).getModel().equals(model)) {
                                            if (((Vehicle)this.database.getListing(i)).getBodyType().equals(bodyType)) {
                                                if (((Vehicle)this.database.getListing(i)).getYearOfManufacture() > yearOfManufacture) {
                                                    if (((Vehicle)this.database.getListing(i)).getDrivenKm() < drivenKm) {
                                                        if (((Vehicle)this.database.getListing(i)).getPower() > power) {
                                                            if (((Vehicle)this.database.getListing(i)).getPrice() < price) {
                                                                if (subtype.equals("Car")) {
                                                                    if (this.database.getListing(i) instanceof Car) {
                                                                        this.auxiliary.add(this.database.getListing(i));
                                                                    }
                                                                } else if (subtype.equals("Motorcycle")) {
                                                                    if (this.database.getListing(i) instanceof Motorcycle) {
                                                                        this.auxiliary.add(this.database.getListing(i));
                                                                    }
                                                                } else if (subtype.equals("Truck")) {
                                                                    if (this.database.getListing(i) instanceof Truck) {
                                                                        this.auxiliary.add(this.database.getListing(i));
                                                                    }
                                                                } else {
                                                                    if (this.database.getListing(i) instanceof Bus) {
                                                                        this.auxiliary.add(this.database.getListing(i));
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        } else {
                            for (int i = 0; i < this.database.getCount(); i++) {
                                if (this.database.getListing(i) instanceof Vehicle) {
                                    if (true) {
                                        if (((Vehicle)this.database.getListing(i)).getModel().equals(model)) {
                                            if (((Vehicle)this.database.getListing(i)).getYearOfManufacture() > yearOfManufacture) {
                                                if (((Vehicle)this.database.getListing(i)).getDrivenKm() < drivenKm) {
                                                    if (((Vehicle)this.database.getListing(i)).getPower() > power) {
                                                        if (((Vehicle)this.database.getListing(i)).getPrice() < price) {
                                                            if (subtype.equals("Car")) {
                                                                if (this.database.getListing(i) instanceof Car) {
                                                                    this.auxiliary.add(this.database.getListing(i));
                                                                }
                                                            } else if (subtype.equals("Motorcycle")) {
                                                                if (this.database.getListing(i) instanceof Motorcycle) {
                                                                    this.auxiliary.add(this.database.getListing(i));
                                                                }
                                                            } else if (subtype.equals("Truck")) {
                                                                if (this.database.getListing(i) instanceof Truck) {
                                                                    this.auxiliary.add(this.database.getListing(i));
                                                                }
                                                            } else {
                                                                if (this.database.getListing(i) instanceof Bus) {
                                                                    this.auxiliary.add(this.database.getListing(i));
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    } else {
                        if (!bodyType.isEmpty()) {
                            for (int i = 0; i < this.database.getCount(); i++) {
                                if (this.database.getListing(i) instanceof Vehicle) {
                                    if (true) {
                                        if (true) {
                                            if (((Vehicle)this.database.getListing(i)).getBodyType().equals(bodyType)) {
                                                if (((Vehicle)this.database.getListing(i)).getYearOfManufacture() > yearOfManufacture) {
                                                    if (((Vehicle)this.database.getListing(i)).getDrivenKm() < drivenKm) {
                                                        if (((Vehicle)this.database.getListing(i)).getPower() > power) {
                                                            if (((Vehicle)this.database.getListing(i)).getPrice() < price) {
                                                                if (subtype.equals("Car")) {
                                                                    if (this.database.getListing(i) instanceof Car) {
                                                                        this.auxiliary.add(this.database.getListing(i));
                                                                    }
                                                                } else if (subtype.equals("Motorcycle")) {
                                                                    if (this.database.getListing(i) instanceof Motorcycle) {
                                                                        this.auxiliary.add(this.database.getListing(i));
                                                                    }
                                                                } else if (subtype.equals("Truck")) {
                                                                    if (this.database.getListing(i) instanceof Truck) {
                                                                        this.auxiliary.add(this.database.getListing(i));
                                                                    }
                                                                } else {
                                                                    if (this.database.getListing(i) instanceof Bus) {
                                                                        this.auxiliary.add(this.database.getListing(i));
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        } else {
                            for (int i = 0; i < this.database.getCount(); i++) {
                                if (this.database.getListing(i) instanceof Vehicle) {
                                    if (true) {
                                        if (true) {
                                            if (((Vehicle)this.database.getListing(i)).getYearOfManufacture() > yearOfManufacture) {
                                                if (((Vehicle)this.database.getListing(i)).getDrivenKm() < drivenKm) {
                                                    if (((Vehicle)this.database.getListing(i)).getPower() > power) {
                                                        if (((Vehicle)this.database.getListing(i)).getPrice() < price) {
                                                            if (subtype.equals("Car")) {
                                                                if (this.database.getListing(i) instanceof Car) {
                                                                    this.auxiliary.add(this.database.getListing(i));
                                                                }
                                                            } else if (subtype.equals("Motorcycle")) {
                                                                if (this.database.getListing(i) instanceof Motorcycle) {
                                                                    this.auxiliary.add(this.database.getListing(i));
                                                                }
                                                            } else if (subtype.equals("Truck")) {
                                                                if (this.database.getListing(i) instanceof Truck) {
                                                                    this.auxiliary.add(this.database.getListing(i));
                                                                }
                                                            } else {
                                                                if (this.database.getListing(i) instanceof Bus) {
                                                                    this.auxiliary.add(this.database.getListing(i));
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                } 
            }
        } else if (type.equals("Garden machines")) {
            if (!brand.isEmpty()) {
                for (int i = 0; i < this.database.getCount(); i++) {
                    if (this.database.getListing(i) instanceof Machine) {
                        if (((Machine)this.database.getListing(i)).getYearOfManufacture() > yearOfManufacture) {
                            if (((Machine)this.database.getListing(i)).getPowerInKw() > power) {
                                if (((Machine)this.database.getListing(i)).getPrice() < price) {
                                    if (((Machine)this.database.getListing(i)).getBrand().equals(brand)) {
                                        if (subtype.equals("Lawn Mower")) {
                                            if (this.database.getListing(i) instanceof LawnMower) {
                                                this.auxiliary.add(this.database.getListing(i));
                                            }
                                        } else if (subtype.equals("Brush Cutter")) {
                                            if (this.database.getListing(i) instanceof BrushCutter) {
                                                this.auxiliary.add(this.database.getListing(i));
                                            }
                                        } else {
                                            if (this.database.getListing(i) instanceof Chainsaw) {
                                                this.auxiliary.add(this.database.getListing(i));
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            } else {
                for (int i = 0; i < this.database.getCount(); i++) {
                    if (this.database.getListing(i) instanceof Machine) {
                        if (((Machine)this.database.getListing(i)).getYearOfManufacture() > yearOfManufacture) {
                            if (((Machine)this.database.getListing(i)).getPowerInKw() > power) {
                                if (((Machine)this.database.getListing(i)).getPrice() < price) {
                                    if (true) { 
                                        if (subtype.equals("Lawn Mower")) {
                                            if (this.database.getListing(i) instanceof LawnMower) {
                                                this.auxiliary.add(this.database.getListing(i));
                                            }
                                        } else if (subtype.equals("Brush Cutter")) {
                                            if (this.database.getListing(i) instanceof BrushCutter) {
                                                this.auxiliary.add(this.database.getListing(i));
                                            }
                                        } else {
                                            if (this.database.getListing(i) instanceof Chainsaw) {
                                                this.auxiliary.add(this.database.getListing(i));
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        } else if (type.equals("Electronics")) {
            if (!brand.isEmpty()) {
                for (int i = 0; i < this.database.getCount(); i++) {
                    if (this.database.getListing(i) instanceof ElectronicDevice) {
                        if (((ElectronicDevice)this.database.getListing(i)).getYearOfManufacture() > yearOfManufacture) {
                            if (true) {
                                if (((ElectronicDevice)this.database.getListing(i)).getPrice() < price) {
                                    if (((ElectronicDevice)this.database.getListing(i)).getBrand().equals(brand)) {
                                        if (subtype.equals("Other")) {
                                            if (this.database.getListing(i) instanceof Electronics) {
                                                this.auxiliary.add(this.database.getListing(i));
                                            }
                                        } else if (subtype.equals("Computer")) {
                                            if (this.database.getListing(i) instanceof Computer) {
                                                if (this.database.getListing(i) instanceof Computer) {
                                                    if (((Computer)this.database.getListing(i)).getProcessorFrequency() > frequency) {
                                                        if (((Computer)this.database.getListing(i)).getRam() > ram) {
                                                            this.auxiliary.add(this.database.getListing(i));
                                                        }
                                                    }
                                                }
                                            }
                                        } else {
                                            if (this.database.getListing(i) instanceof Mobile) {
                                                if (((Mobile)this.database.getListing(i)).getProcessorFrequency() > frequency) {
                                                    if (((Mobile)this.database.getListing(i)).getRam() > ram) {
                                                        this.auxiliary.add(this.database.getListing(i));
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            } else {
                for (int i = 0; i < this.database.getCount(); i++) {
                    if (this.database.getListing(i) instanceof ElectronicDevice) {
                        if (((ElectronicDevice)this.database.getListing(i)).getYearOfManufacture() > yearOfManufacture) {
                            if (true) {
                                if (((ElectronicDevice)this.database.getListing(i)).getPrice() < price) {
                                    if (true) { 
                                        if (subtype.equals("Other")) {
                                            if (this.database.getListing(i) instanceof Electronics) {
                                                this.auxiliary.add(this.database.getListing(i));
                                            }
                                        } else if (subtype.equals("Computer")) {
                                            if (this.database.getListing(i) instanceof Computer) {
                                                if (((Computer)this.database.getListing(i)).getProcessorFrequency() > frequency) {
                                                    if (((Computer)this.database.getListing(i)).getRam() > ram) {
                                                        this.auxiliary.add(this.database.getListing(i));
                                                    }
                                                }
                                            }
                                        } else {
                                            if (this.database.getListing(i) instanceof Mobile) {
                                                if (((Mobile)this.database.getListing(i)).getProcessorFrequency() > frequency) {
                                                    if (((Mobile)this.database.getListing(i)).getRam() > ram) {
                                                        this.auxiliary.add(this.database.getListing(i));
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        if (this.auxiliary.size() == 0) {
            throw new InvalidSearchParametersException("type: " + type + ", subtype: " + subtype + ", brand: " + brand + ", model: " + model + ", year of manufacture: " + yearOfManufacture + ", power: " + power + ", driven km: " + drivenKm + ", price: " + price + ", body type: " + bodyType + ", processor frequency: " + frequency + ", ram: " + ram);
        }
        return this.auxiliary;
    }
    
    private void TF10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseGraphics(new Listing()).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L00;
    private javax.swing.JLabel L01;
    private javax.swing.JLabel L03;
    private javax.swing.JLabel L10;
    private javax.swing.JLabel L11;
    private javax.swing.JLabel L20;
    private javax.swing.JLabel L21;
    private javax.swing.JLabel L30;
    private javax.swing.JLabel L40;
    private javax.swing.JLabel L50;
    private javax.swing.JTextField TF00;
    private javax.swing.JTextField TF01;
    private javax.swing.JTextField TF03;
    private javax.swing.JTextField TF10;
    private javax.swing.JTextField TF11;
    private javax.swing.JTextField TF20;
    private javax.swing.JTextField TF21;
    private javax.swing.JTextField TF30;
    private javax.swing.JTextField TF40;
    private javax.swing.JTextField TF50;
    private javax.swing.JButton searchB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> categoryCB;
    private javax.swing.JComboBox<String> choiceCB;
    private javax.swing.JLabel choiceLabel;
    // End of variables declaration//GEN-END:variables
}
