/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bazaar;

import electronics.Electronics;
import electronics.Mobile;
import electronics.Computer;
import java.awt.event.WindowEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import owner.Person;
import onWheels.Car;
import onWheels.Bus;
import onWheels.Truck;
import onWheels.Motorcycle;
import gardenMachines.LawnMower;
import gardenMachines.BrushCutter;
import gardenMachines.Chainsaw;

/**
 *
 * @author Tomáš
 */
public class SaleGraphics extends javax.swing.JFrame {
    private Listing listing;
    private static SaleGraphics instance = null;
    /**
     * Creates new form SaleGraphics
     */
    
    public static SaleGraphics getInstance (Listing listing) {
        if (instance == null) {
            instance = new SaleGraphics(listing);
        } 
        return instance;
    }  
    
    private SaleGraphics(Listing listing) {
        initComponents();
        this.listing = listing;
        this.choiceL.setVisible(false);;
        this.choiceCB.setVisible(false);
        this.L70.setVisible(false);
        this.T70.setVisible(false);
        this.L60.setVisible(false);
        this.T60.setVisible(false);
        this.L10.setVisible(false);
        this.T10.setVisible(false);
        this.L50.setVisible(false);
        this.T50.setVisible(false);
        this.L40.setVisible(false);
        this.T40.setVisible(false);
        this.L80.setVisible(false);
        this.T80.setVisible(false);
        this.L30.setVisible(false);
        this.T30.setVisible(false);
        this.choiceL.setVisible(false);
        this.L20.setVisible(false);
        this.T20.setVisible(false);
        this.L00.setVisible(false);
        this.T00.setVisible(false);
        this.L01.setVisible(false);
        this.L11.setVisible(false);
        this:T01.setVisible(false);
        this.T11.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        typeL = new javax.swing.JLabel();
        typeCB = new javax.swing.JComboBox<>();
        choiceL = new javax.swing.JLabel();
        choiceCB = new javax.swing.JComboBox<>();
        L00 = new javax.swing.JLabel();
        L10 = new javax.swing.JLabel();
        L20 = new javax.swing.JLabel();
        L30 = new javax.swing.JLabel();
        L40 = new javax.swing.JLabel();
        L50 = new javax.swing.JLabel();
        L60 = new javax.swing.JLabel();
        L70 = new javax.swing.JLabel();
        L80 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        T00 = new javax.swing.JTextField();
        T10 = new javax.swing.JTextField();
        T20 = new javax.swing.JTextField();
        T30 = new javax.swing.JTextField();
        T40 = new javax.swing.JTextField();
        T50 = new javax.swing.JTextField();
        T60 = new javax.swing.JTextField();
        T70 = new javax.swing.JTextField();
        T80 = new javax.swing.JTextField();
        priceT = new javax.swing.JTextField();
        commentT = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        firstNameT = new javax.swing.JTextField();
        lastNameT = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dayT = new javax.swing.JTextField();
        monthT = new javax.swing.JTextField();
        yearT = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cityT = new javax.swing.JTextField();
        phoneT = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        addB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        L01 = new javax.swing.JLabel();
        L11 = new javax.swing.JLabel();
        T01 = new javax.swing.JTextField();
        T11 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Welcome to the listing addition section. Continue by selecting options.");

        typeL.setText("Choose listing type");

        typeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vehicle", "Garden Machine", "Electronics" }));
        typeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeCBActionPerformed(evt);
            }
        });

        choiceL.setText("Choose vehicle type");

        choiceCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose...", "Car", "Motorcycle", "Truck", "Bus" }));
        choiceCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceCBActionPerformed(evt);
            }
        });

        L00.setText("Brand");

        L10.setText("Model");

        L20.setText("Power");

        L30.setText("Year of manufacture");

        L40.setText("Engine displacement");

        L50.setText("Driven km");

        L60.setText("Body type");

        L70.setText("Color");

        L80.setText("Fuel");

        jLabel11.setText("Price");

        jLabel12.setText("Your comment");

        T00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T00ActionPerformed(evt);
            }
        });

        T10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T10ActionPerformed(evt);
            }
        });

        T20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T20ActionPerformed(evt);
            }
        });

        T40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T40ActionPerformed(evt);
            }
        });

        T70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T70ActionPerformed(evt);
            }
        });

        priceT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTActionPerformed(evt);
            }
        });

        commentT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentTActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Your personal details");

        jLabel14.setText("First name");

        jLabel15.setText("Last name");

        jLabel16.setText("Day");

        jLabel17.setText("Month");

        jLabel18.setText("Year");

        monthT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthTActionPerformed(evt);
            }
        });

        jLabel19.setText("City");

        jLabel20.setText("Phone no.");

        cityT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTActionPerformed(evt);
            }
        });

        phoneT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTActionPerformed(evt);
            }
        });

        jLabel21.setText("Date of birth");

        addB.setText("Add listing");
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });

        jLabel2.setText("€");

        L01.setText("jLabel3");

        L11.setText("jLabel4");

        T01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T01ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(37, 37, 37)
                                    .addComponent(firstNameT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lastNameT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cityT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(L00)
                                .addComponent(choiceL)
                                .addComponent(L10)
                                .addComponent(L30)
                                .addComponent(L40)
                                .addComponent(L50)
                                .addComponent(L60)
                                .addComponent(L70)
                                .addComponent(L80)
                                .addComponent(L20)))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel16))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(dayT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(monthT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(yearT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(111, 111, 111)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addGap(18, 18, 18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(T01, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(T11, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(priceT, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(phoneT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(T00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(choiceCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(T10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(T20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(T30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(T40, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(T50, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(T60, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(T70, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(T80, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(124, 124, 124)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(L01)
                                    .addComponent(L11)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(typeL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(typeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(268, 268, 268)))
                .addGap(18, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(commentT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(addB))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeL)
                    .addComponent(typeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choiceCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choiceL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L00)
                    .addComponent(T00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L01)
                    .addComponent(T01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L10)
                    .addComponent(T10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L11)
                    .addComponent(T11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L30)
                    .addComponent(T30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L40)
                    .addComponent(T40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L50, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L60)
                    .addComponent(T60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L70)
                    .addComponent(T70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L80)
                    .addComponent(T80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cityT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(dayT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(monthT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(phoneT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(priceT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(yearT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(12, 12, 12)
                        .addComponent(commentT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(addB)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Sets components invisible
     */
    private void setInvisibleComponents() {
        this.L70.setVisible(false);
        this.T70.setVisible(false);
        this.L60.setVisible(false);
        this.T60.setVisible(false);
        this.L10.setVisible(false);
        this.T10.setVisible(false);
        this.L50.setVisible(false);
        this.T50.setVisible(false);
        this.L40.setVisible(false);
        this.T40.setVisible(false);
        this.L80.setVisible(false);
        this.T80.setVisible(false);
        this.L30.setVisible(false);
        this.T30.setVisible(false);
        this.L20.setVisible(false);
        this.T20.setVisible(false);
        this.L00.setVisible(false);
        this.T00.setVisible(false);
        this.L01.setVisible(false);
        this.L11.setVisible(false);
        this:T01.setVisible(false);
        this.T11.setVisible(false);
        
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(null, "Do you really want to quit, your data will be lost", "Exit", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            dispose();
        }
        
    }//GEN-LAST:event_formWindowClosing
    /**
     * Makes individual labels and text fields visible based on the combo box condition
     * @param evt 
     */
    private void choiceCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceCBActionPerformed
        // TODO add your handling code here:
       if(typeCB.getSelectedIndex() == 0) {
           if (choiceCB.getSelectedIndex() == 0) {
               this.setInvisibleComponents();
               this.L00.setVisible(true);
               this.L00.setText("Brand");
               this.T00.setVisible(true);
               this.L10.setVisible(true);
               this.L10.setText("Model");
               this.T10.setVisible(true);
               this.L20.setVisible(true);
               this.L20.setText("Power");
               this.T20.setVisible(true);
               this.L30.setVisible(true);
               this.L30.setText("YearOfManufacture");
               this.T30.setVisible(true);
               this.L40.setVisible(true);
               this.L40.setText("Engine displacement");
               this.T40.setVisible(true);
               this.L50.setVisible(true);
               this.L50.setText("Driven km");
               this.T50.setVisible(true);
               this.L60.setVisible(true);
               this.L60.setText("Body type");
               this.T60.setVisible(true);
               this.L70.setVisible(true);
               this.L70.setText("Color");
               this.T70.setVisible(true);
               this.L80.setVisible(true);
               this.L80.setText("Fuel");
               this.T80.setVisible(true);
           } else if (choiceCB.getSelectedIndex() == 1) {
               this.setInvisibleComponents();
               this.L00.setVisible(true);
               this.L00.setText("Brand");
               this.T00.setVisible(true);
               this.L10.setVisible(true);
               this.L10.setText("Model");
               this.T10.setVisible(true);
               this.L20.setVisible(true);
               this.L20.setText("Power");
               this.T20.setVisible(true);
               this.L30.setVisible(true);
               this.L30.setText("YearOfManufacture");
               this.T30.setVisible(true);
               this.L40.setVisible(true);
               this.L40.setText("Engine displacement");
               this.T40.setVisible(true);
               this.L50.setVisible(true);
               this.L50.setText("Driven km");
               this.T50.setVisible(true);
               this.L60.setVisible(true);
               this.L60.setText("Body type");
               this.T60.setVisible(true);
               this.L70.setVisible(true);
               this.L70.setText("Color");
               this.T70.setVisible(true);
               this.L80.setVisible(true);
               this.L80.setText("Fuel");
               this.T80.setVisible(true);
           } else if (choiceCB.getSelectedIndex() == 2) {
               this.setInvisibleComponents();
               this.L00.setVisible(true);
               this.L00.setText("Brand");
               this.T00.setVisible(true);
               this.L10.setVisible(true);
               this.L10.setText("Model");
               this.T10.setVisible(true);
               this.L20.setVisible(true);
               this.L20.setText("Power");
               this.T20.setVisible(true);
               this.L30.setVisible(true);
               this.L30.setText("YearOfManufacture");
               this.T30.setVisible(true);
               this.L40.setVisible(true);
               this.L40.setText("Engine displacement");
               this.T40.setVisible(true);
               this.L50.setVisible(true);
               this.L50.setText("Driven km");
               this.T50.setVisible(true);
               this.L60.setVisible(true);
               this.L60.setText("Body type");
               this.T60.setVisible(true);
               this.L70.setVisible(true);
               this.L70.setText("Color");
               this.T70.setVisible(true);
               this.L80.setVisible(true);
               this.L80.setText("Fuel");
               this.T80.setVisible(true);
               this.L01.setVisible(true);
               this.L01.setText("Emission cl.");
               this.L11.setVisible(true);
               this.L11.setText("Seat count");
               this:T01.setVisible(true);
               this.T11.setVisible(true);
           } else if (choiceCB.getSelectedIndex() == 3) {
               this.setInvisibleComponents();
               this.L00.setVisible(true);
               this.L00.setText("Brand");
               this.T00.setVisible(true);
               this.L10.setVisible(true);
               this.L10.setText("Model");
               this.T10.setVisible(true);
               this.L20.setVisible(true);
               this.L20.setText("Power");
               this.T20.setVisible(true);
               this.L30.setVisible(true);
               this.L30.setText("YearOfManufacture");
               this.T30.setVisible(true);
               this.L40.setVisible(true);
               this.L40.setText("Engine displacement");
               this.T40.setVisible(true);
               this.L50.setVisible(true);
               this.L50.setText("Driven km");
               this.T50.setVisible(true);
               this.L60.setVisible(true);
               this.L60.setText("Body type");
               this.T60.setVisible(true);
               this.L70.setVisible(true);
               this.L70.setText("Color");
               this.T70.setVisible(true);
               this.L80.setVisible(true);
               this.L80.setText("Fuel");
               this.T80.setVisible(true);
               this.L01.setVisible(true);
               this.L01.setText("Emission cl.");
               this.L11.setVisible(true);
               this.L11.setText("Load capacity");
               this:T01.setVisible(true);
               this.T11.setVisible(true);
           }
       } else if (typeCB.getSelectedIndex() == 1) {
           this.setInvisibleComponents();
            this.L00.setVisible(true);
            this.L00.setText("Brand");
            this.T00.setVisible(true);
            this.L10.setVisible(true);
            this.L10.setText("Months of use");
            this.T10.setVisible(true);
            this.L20.setVisible(true);
            this.L20.setText("Power input");
            this.T20.setVisible(true);
            this.L30.setVisible(true);
            this.L30.setText("YearOfManufacture");
            this.T30.setVisible(true);
            this.L40.setVisible(true);
            this.L40.setText("Engine displacement");
            this.T40.setVisible(true);
       } else if (typeCB.getSelectedIndex() == 2) {
            if (choiceCB.getSelectedIndex() == 0) {
               this.setInvisibleComponents();
               this.L00.setVisible(true);
               this.L00.setText("Brand");
               this.T00.setVisible(true);
               this.L10.setVisible(true);
               this.L10.setText("YearOfManufacture");
               this.T10.setVisible(true);
               this.L20.setVisible(true);
               this.L20.setText("Months of use");
               this.T20.setVisible(true);
               this.L30.setVisible(true);
               this.L30.setText("Processor frequency");
               this.T30.setVisible(true);
               this.L40.setVisible(true);
               this.L40.setText("RAM");
               this.T40.setVisible(true);
               this.L50.setVisible(true);
               this.L50.setText("Internal storage");
               this.T50.setVisible(true);
               this.L60.setVisible(true);
               this.L60.setText("Display diagonal");
               this.T60.setVisible(true);
           } else if (choiceCB.getSelectedIndex() == 1) {
               this.setInvisibleComponents();
               this.L00.setVisible(true);
               this.L00.setText("Brand");
               this.T00.setVisible(true);
               this.L10.setVisible(true);
               this.L10.setText("YearOfManufacture");
               this.T10.setVisible(true);
               this.L20.setVisible(true);
               this.L20.setText("Months of use");
               this.T20.setVisible(true);
               this.L30.setVisible(true);
               this.L30.setText("Processor frequency");
               this.T30.setVisible(true);
               this.L40.setVisible(true);
               this.L40.setText("RAM");
               this.T40.setVisible(true);
               this.L50.setVisible(true);
               this.L50.setText("Internal storage");
               this.T50.setVisible(true);
               this.L60.setVisible(true);
               this.L60.setText("Battery life");
               this.T60.setVisible(true);
               this.L70.setVisible(true);
               this.L70.setText("Camera resolution");
               this.T70.setVisible(true);
           } else if (choiceCB.getSelectedIndex() == 2) {
               this.setInvisibleComponents();
               this.L00.setVisible(true);
               this.L00.setText("Brand");
               this.T00.setVisible(true);
               this.L10.setVisible(true);
               this.L10.setText("YearOfManufacture");
               this.T10.setVisible(true);
               this.L20.setVisible(true);
               this.L20.setText("Months of use");
               this.T20.setVisible(true);
           }
       }
    }//GEN-LAST:event_choiceCBActionPerformed
    /**
     * Sets the subordinate combo box based on the parent combo box
     * @param evt 
     */
    
    private void typeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeCBActionPerformed
        // TODO add your handling code here:
        if (typeCB.getSelectedIndex() == 0) {
            this.setInvisibleComponents();
            this.choiceL.setVisible(true);
            this.choiceL.setText("Select vehicle type");
            this.choiceCB.setVisible(true);
            this.choiceCB.removeAllItems();
            this.choiceCB.insertItemAt("Car",0);
            this.choiceCB.insertItemAt("Motorcycle",1);
            this.choiceCB.insertItemAt("Bus",2);
            this.choiceCB.insertItemAt("Truck",3);
        } else if (typeCB.getSelectedIndex() == 1) {
            this.setInvisibleComponents();
            this.choiceL.setVisible(true);
            this.choiceL.setText("Select machine type");
            this.choiceCB.setVisible(true);
            this.choiceCB.removeAllItems();
            this.choiceCB.insertItemAt("Lawn Mower",0);
            this.choiceCB.insertItemAt("Brush Cutter",1);
            this.choiceCB.insertItemAt("Chainsaw",2);
        } else if (typeCB.getSelectedIndex() == 2) {
            this.setInvisibleComponents();
            this.choiceL.setVisible(true);
            this.choiceL.setText("Select electronics type");
            this.choiceCB.setVisible(true);
            this.choiceCB.removeAllItems();
            this.choiceCB.insertItemAt("Computer",0);
            this.choiceCB.insertItemAt("Mobile",1);
            this.choiceCB.insertItemAt("Other",2);
        }
    }//GEN-LAST:event_typeCBActionPerformed

    private void T10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T10ActionPerformed

    private void T20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T20ActionPerformed

    private void T40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T40ActionPerformed

    private void priceTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTActionPerformed

    private void T70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T70ActionPerformed

    private void monthTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthTActionPerformed

    private void commentTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commentTActionPerformed

    private void cityTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTActionPerformed

    private void phoneTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTActionPerformed
    /**
     * Pressing the add button iterates through all text fields and collects data for the listing.
     * In case of an error, throws exceptions of various types.
     * After adding, immediately saves the database to a file.
     * @param evt 
     */
    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed
        // TODO add your handling code here:
        int errors = 0;
        String brand = "";
        String model = "";
        String bodyType = "";
        String color = "";
        String fuel = "";
        int power = 0;
        int drivenKm = 0;
        int yearOfManufacture = 0;
        double engineDisplacement = 0;
        String emissionClass = "";
        int loadCapacity = 0;
        int seatCount = 0;
        int monthsOfUse = 0;
        int frequency = 0;
        double ram = 0;
        double internalStorage = 0;
        int batteryLife = 0;
        int displayDiagonal = 0;  
        int cameraResolution = 0;
        String firstName = "";
        String lastName = "";
        String city = "";
        int day = 0;
        int month = 0;
        int year = 0;
        int price = 0;
        long phone = 0;
        String comment = "";
        if (this.typeCB.getSelectedIndex() == 0) {
            brand = "";
            model = "";
            bodyType = "";
            color = "";
            fuel = "";
            power = 0;
            drivenKm = 0;
            yearOfManufacture = 0;
            engineDisplacement = 0;
            emissionClass = "";
            loadCapacity = 0;
            seatCount = 0;
            monthsOfUse = 0;
            frequency = 0;
            ram = 0;
            internalStorage = 0;
            batteryLife = 0;
            displayDiagonal = 0;  
            cameraResolution = 0;
            if (true) {
                brand = "";
                model = "";
                bodyType = "";
                color = "";
                fuel = "";
                power = 0;
                drivenKm = 0;
                yearOfManufacture = 0;
                engineDisplacement = 0;
                emissionClass = "";
                loadCapacity = 0;
                seatCount = 0;
                monthsOfUse = 0;
                frequency = 0;
                ram = 0;
                internalStorage = 0;
                batteryLife = 0;
                displayDiagonal = 0;  
                cameraResolution = 0;
                if (!this.T00.getText().isEmpty()) {
                    brand = this.T00.getText();
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid brand");
                    errors++;       
                }
                if (!this.T10.getText().isEmpty()){
                    model = this.T10.getText();
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid model");
                    errors++;
                } 
                try {
                    power = Integer.parseInt(this.T20.getText());
                    if(power < 0) {
                        power = Integer.parseInt("bad");
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Incorrectly entered power");
                    errors++;    
                }
                try {
                    yearOfManufacture = Integer.parseInt(this.T30.getText());
                    if(yearOfManufacture < 0) {
                        yearOfManufacture = Integer.parseInt("bad");
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Incorrectly entered year of manufacture");
                    errors++;    
                }
                try {
                    engineDisplacement = Double.parseDouble(this.T40.getText());
                    if(engineDisplacement < 0) {
                        engineDisplacement = Double.parseDouble("bad");
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Incorrectly entered engine displacement");
                    errors++;    
                }
                try {
                    drivenKm = Integer.parseInt(this.T50.getText());
                    if(drivenKm < 0) {
                        drivenKm = Integer.parseInt("bad");
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Incorrectly entered driven kilometres");
                    errors++;    
                }
                if (!this.T60.getText().isEmpty()){
                    bodyType = this.T60.getText();
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid body type");
                    errors++;
                }
                if (!this.T70.getText().isEmpty()){
                    color = this.T70.getText();
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid color");
                    errors++;
                }
                if (!this.T80.getText().isEmpty()){
                    fuel = this.T80.getText();
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid fuel");
                    errors++;
                }  
                if (this.choiceCB.getSelectedIndex() == 2) {
                    if (!this.T01.getText().isEmpty()){
                        emissionClass = this.T01.getText();
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid emission class");
                        errors++;
                    }
                    try {
                        seatCount = Integer.parseInt(this.T11.getText());
                        if(seatCount < 0) {
                            seatCount = Integer.parseInt("bad");
                        }
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Incorrectly entered seat count");
                        errors++;    
                    }
                } else if (this.choiceCB.getSelectedIndex() == 3) {
                    if (!this.T01.getText().isEmpty()){
                        emissionClass = this.T01.getText();
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid emission class");
                        errors++;
                    }
                    try {
                        loadCapacity = Integer.parseInt(this.T11.getText());
                        if(loadCapacity < 0) {
                            loadCapacity = Integer.parseInt("bad");
                        }
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Incorrectly entered load capacity");
                        errors++;    
                    } 
                }
            }
        } else if (this.typeCB.getSelectedIndex() == 1) {
            brand = "";
            model = "";
            bodyType = "";
            color = "";
            fuel = "";
            power = 0;
            drivenKm = 0;
            yearOfManufacture = 0;
            engineDisplacement = 0;
            emissionClass = "";
            loadCapacity = 0;
            seatCount = 0;
            monthsOfUse = 0;
            frequency = 0;
            ram = 0;
            internalStorage = 0;
            batteryLife = 0;
            displayDiagonal = 0;  
            cameraResolution = 0;
            if (!this.T00.getText().isEmpty()) {
                brand = this.T00.getText();
            } else {
                JOptionPane.showMessageDialog(null, "Invalid brand");
                errors++;       
            }
            try {
                monthsOfUse = Integer.parseInt(this.T10.getText());
                if(monthsOfUse < 0) {
                    monthsOfUse = Integer.parseInt("bad");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Incorrectly entered months of use");
                errors++;    
            }
            try {
                power = Integer.parseInt(this.T20.getText());
                if(power < 0) {
                    power = Integer.parseInt("bad");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Incorrectly entered power input");
                errors++;    
            }
            try {
                yearOfManufacture = Integer.parseInt(this.T30.getText());
                if(yearOfManufacture < 0) {
                    yearOfManufacture = Integer.parseInt("bad");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Incorrectly entered year of manufacture");
                errors++;    
            }
            try {
                engineDisplacement = Double.parseDouble(this.T40.getText());
                if(engineDisplacement < 0) {
                    engineDisplacement = Double.parseDouble("bad");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Incorrectly entered engine displacement");
                errors++;    
            }
        } else if (typeCB.getSelectedIndex() == 2) {
            brand = "";
            model = "";
            bodyType = "";
            color = "";
            fuel = "";
            power = 0;
            drivenKm = 0;
            yearOfManufacture = 0;
            engineDisplacement = 0;
            emissionClass = "";
            loadCapacity = 0;
            seatCount = 0;
            monthsOfUse = 0;
            frequency = 0;
            ram = 0;
            internalStorage = 0;
            batteryLife = 0;
            displayDiagonal = 0;  
            cameraResolution = 0;
            if (!this.T00.getText().isEmpty()) {
                brand = this.T00.getText();
            } else {
                JOptionPane.showMessageDialog(null, "Invalid brand");
                errors++;       
            }
            try {
                yearOfManufacture = Integer.parseInt(this.T10.getText());
                if(yearOfManufacture < 0) {
                    yearOfManufacture = Integer.parseInt("bad");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Incorrectly entered year of manufacture");
                errors++;    
            }
            try {
                monthsOfUse = Integer.parseInt(this.T20.getText());
                if(monthsOfUse < 0) {
                    monthsOfUse = Integer.parseInt("bad");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Incorrectly entered months of use");
                errors++;    
            } 
            if (choiceCB.getSelectedIndex() == 0 || choiceCB.getSelectedIndex() == 1) {
                try {
                    frequency = Integer.parseInt(this.T30.getText());
                    if(frequency < 0) {
                     frequency = Integer.parseInt("bad");
                    }   
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Incorrectly entered processor frequency");
                    errors++;    
                }
                try {
                    ram = Double.parseDouble(this.T40.getText());
                    if(ram < 0) {
                     ram = Double.parseDouble("bad");
                    }   
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Incorrectly entered ram");
                    errors++;    
                }
                try {
                    internalStorage = Double.parseDouble(this.T50.getText());
                    if(internalStorage < 0) {
                     internalStorage = Double.parseDouble("bad");
                    }   
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Incorrectly entered internal storage");
                    errors++;    
                }
                if (choiceCB.getSelectedIndex() == 0) {
                    try {
                        displayDiagonal = Integer.parseInt(this.T60.getText());
                        if(displayDiagonal < 0) {
                         displayDiagonal = Integer.parseInt("bad");
                        }   
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Incorrectly entered display diagonal");
                        errors++;    
                    }
                } else if (choiceCB.getSelectedIndex() == 1) {
                    try {
                        batteryLife = Integer.parseInt(this.T60.getText());
                        if(batteryLife < 0) {
                         batteryLife = Integer.parseInt("bad");
                        }   
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Incorrectly entered battery life");
                        errors++;    
                    }
                    try {
                        cameraResolution = Integer.parseInt(this.T70.getText());
                        if (cameraResolution < 0) {
                         cameraResolution = Integer.parseInt("bad");
                        }   
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Incorrectly entered battery life");
                        errors++;    
                    }
                }
            }
        }
            if (!this.firstNameT.getText().isEmpty()) {
                firstName = this.firstNameT.getText();
            } else {
                JOptionPane.showMessageDialog(null, "Invalid first name");
                errors++;
            }
            if (!this.lastNameT.getText().isEmpty()) {
                lastName = this.lastNameT.getText();
            } else {
                JOptionPane.showMessageDialog(null, "Invalid last name");
                errors++;
            }
            if (!this.cityT.getText().isEmpty()) {
                city = this.cityT.getText();
            } else {
                JOptionPane.showMessageDialog(null, "Invalid city");
                errors++;
            }
            try {
                day = Integer.parseInt(this.dayT.getText());
                if(day < 0 || day > 31) {
                    day = Integer.parseInt("bad");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Incorrectly entered day");
                errors++;    
            }
            try {
                month = Integer.parseInt(this.monthT.getText());
                if(month < 0 || month > 12) {
                    month = Integer.parseInt("bad");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Incorrectly entered month");
                errors++;    
            }
            try {
                year = Integer.parseInt(this.yearT.getText());
                if(year < 0) {
                    year = Integer.parseInt("bad");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Incorrectly entered year");
                errors++;    
            }
            try {
                price = Integer.parseInt(this.priceT.getText());
                if(price < 0) {
                    price = Integer.parseInt("bad");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Incorrectly entered price");
                errors++;    
            }
            try {
                phone = Long.parseLong(this.phoneT.getText());
                if(phone < 0 ) {
                    phone = Long.parseLong("bad");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Incorrectly entered phone number");
                errors++;    
            }
            comment = this.commentT.getText();
            IForSale newListing = null;
            if (errors == 0) {
                if (choiceCB.getSelectedItem().equals("Car")) {
                    newListing = new Car(new Person(firstName,lastName,day,month,year,city,phone),"Car",brand,model,power,yearOfManufacture,engineDisplacement,drivenKm,bodyType,color,price,fuel,comment);
                } else if (choiceCB.getSelectedItem().equals("Motorcycle")) {
                    newListing = new Motorcycle(new Person(firstName,lastName,day,month,year,city,phone),"Motorcycle",brand,model,power,yearOfManufacture,engineDisplacement,drivenKm,bodyType,color,price,fuel,comment);
                } else if (choiceCB.getSelectedItem().equals("Bus")) {
                    newListing = new Bus(new Person(firstName,lastName,day,month,year,city,phone),"Bus",brand,model,power,yearOfManufacture,engineDisplacement,drivenKm,bodyType,color,price,fuel ,seatCount ,emissionClass,comment);
                } else if (choiceCB.getSelectedItem().equals("Truck")) {
                    newListing = new Truck(new Person(firstName,lastName,day,month,year,city,phone),"Truck",brand,model,power,yearOfManufacture,engineDisplacement,drivenKm,bodyType,color,price, fuel, loadCapacity, emissionClass,comment);
                } else if (choiceCB.getSelectedItem().equals("Lawn Mower")) {
                    newListing = new LawnMower(new Person(firstName,lastName,day,month,year,city,phone),"LawnMower",power,engineDisplacement,brand,yearOfManufacture,monthsOfUse,price,comment);
                } else if (choiceCB.getSelectedItem().equals("Brush Cutter")) {
                    newListing = new BrushCutter(new Person(firstName,lastName,day,month,year,city,phone),"BrushCutter",power,engineDisplacement,brand,yearOfManufacture,monthsOfUse,price,comment);
                } else if (choiceCB.getSelectedItem().equals("Chainsaw")) {
                    newListing = new Chainsaw(new Person(firstName,lastName,day,month,year,city,phone),"Chainsaw",power,engineDisplacement,brand,yearOfManufacture,monthsOfUse,price,comment);
                } else if (choiceCB.getSelectedItem().equals("Computer")) {
                    newListing = new Computer(new Person(firstName,lastName,day,month,year,city,phone),"Computer",brand,yearOfManufacture,monthsOfUse,price,frequency,ram,internalStorage,displayDiagonal,comment);
                } else if (choiceCB.getSelectedItem().equals("Mobile")) {
                    newListing = new Mobile(new Person(firstName,lastName,day,month,year,city,phone),"Mobile",brand,yearOfManufacture,monthsOfUse,price,frequency,ram,internalStorage,batteryLife,cameraResolution,comment);
                } else if (choiceCB.getSelectedItem().equals("Other")) {
                    newListing = new Electronics(new Person(firstName,lastName,day,month,year,city,phone),"Electronics",brand,yearOfManufacture,monthsOfUse,price,comment);
                } 
                int reply = JOptionPane.showConfirmDialog(null, newListing.toString(), "Do you really want to add the listing?", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                    this.listing.addListing(newListing);
                    try {
                        this.listing.saveDatabase();
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "An error occurred while adding, please try again");
                        this.listing.removeListing(this.listing.getCount() - 1);
                    }
                }
            }
    }//GEN-LAST:event_addBActionPerformed

    private void T00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T00ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_T00ActionPerformed

    private void T01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T01ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaleGraphics(new Listing()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L00;
    private javax.swing.JLabel L01;
    private javax.swing.JLabel L10;
    private javax.swing.JLabel L11;
    private javax.swing.JLabel L20;
    private javax.swing.JLabel L30;
    private javax.swing.JLabel L40;
    private javax.swing.JLabel L50;
    private javax.swing.JLabel L60;
    private javax.swing.JLabel L70;
    private javax.swing.JLabel L80;
    private javax.swing.JTextField T00;
    private javax.swing.JTextField T01;
    private javax.swing.JTextField T10;
    private javax.swing.JTextField T11;
    private javax.swing.JTextField T20;
    private javax.swing.JTextField T30;
    private javax.swing.JTextField T40;
    private javax.swing.JTextField T50;
    private javax.swing.JTextField T60;
    private javax.swing.JTextField T70;
    private javax.swing.JTextField T80;
    private javax.swing.JTextField priceT;
    private javax.swing.JTextField phoneT;
    private javax.swing.JTextField dayT;
    private javax.swing.JComboBox<String> typeCB;
    private javax.swing.JLabel typeL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JTextField commentT;
    private javax.swing.JTextField firstNameT;
    private javax.swing.JTextField monthT;
    private javax.swing.JTextField cityT;
    private javax.swing.JButton addB;
    private javax.swing.JTextField lastNameT;
    private javax.swing.JTextField yearT;
    private javax.swing.JComboBox<String> choiceCB;
    private javax.swing.JLabel choiceL;
    // End of variables declaration//GEN-END:variables
}
